package com.gym.appointments.Model;

public enum Ubicacion {


    HORIZONTAL_IZQUIERDA_DERECHA,
    HORIZONTAL_DERECHA_IZQUIERDA,
    VERTICAL_ARRIBA_ABAJO,
    VERTICAL_ABAJO_ARRIBA,
    DIAGONAL_IZQUIERDA_DERECHA_ARRIBA_ABAJO,  // DIAGONAL_IZQUIERDA_DERECHA_ARRIBA_ABAJO
    DIAGONAL_DERECHA_IZQUIERDA_ABAJO_ARRIBA,   // DIAGONAL_DERECHA_IZQUIERDA_ABAJO_ARRIBA
    DIAGONAL_IZQUIERDA_DERECHA_ABAJO_ARRIBA,  // DIAGONAL_IZQUIERDA_DERECHA_ABAJO_ARRIBA
    DIAGONAL_DERECHA_IZQUIERDA_ARRIBA_ABAJO;  // DIAGONAL_DERECHA_IZQUIERDA_ARRIBA_ABAJO

}
